data class Game(val ballX:Int,
                val ballY:Int,
                val ballR:Int,
                val ballC:Int,
                val ballT:Int,
                val direction: Int,
                val squareX: Int,
                val squareY: Int,
                val squareSide:Int,
                val squareC:Int,
                val squareT:Int,
                val squareDirection:Int,
                val obstacleX:IntRange,
                val obstacleY: IntRange)